### ISSUE TITLE
11.72: AntiAura incompatibility with QualityArmory

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#10]
**I'll be using this specific issue (#10) as a repo for multiple different bugs that occur with QualityArmory.**

**Screenshot (or a video recording):** 
- Reach: (Reported via private DMs to @joehot200)
- ConsistencyHeadMovementPerHit: Will be added ASAP
- Criticals: Soon
- Occlusion: Soon

**AntiAura version:** 11.72-present

**Server version:** Included in the videos.

**Minecraft version:** 1.15.2

**Check(s) config (if applicable):**
Included in the video. 

**Detailed description of the issue:**
- Reach: Hitting a target with a gun outside the allowed reach limits will flag.
- ConsistencyHeadMovementPerHit: Occasionally flags for ConsistencyHeadMovementPerHit for fast-shooting guns.
- Criticals: Occasionally flags when shooting enemies with Spas-12 (only gun currently tested ATM). Further evidence shows that it may trigger when shooting whilst falling
- Occlusion: Shooting through glass/doors as allowed in the plugin.

**Additional details:**
QualityArmory version is 1.1.169 for all of these bugs.
https://www.spigotmc.org/resources/quality-armory.47561/

**Comment by dodofan** [comment]
@joehot200 This is an update, recording videos of when these happen are super hard. I request that you experiment with it if you have time and go from there. QualityArmory is pretty popular at this point, and the conflicts it has with AntiAura has made me have to remove AntiAura for the time being.

**Comment by dodofan** [comment]
Unmilestoning for now.

**Comment by ghost** [comment]
Not as important because the QA dev added compatibility now for anticheats, which can be toggled on in one of the settings within its configuration. Ignore all the milestone history within this issue.

AA compatibility was supposedly added in September 2020, but it seems to not be working anyway; QA-side compatibility should cover it.
