### ISSUE TITLE
Step, Spider and Jump Check has a problem about /tp

### ISSUE THREAD

**Issue by Qiuscraft** [joehot200/AntiAura#100]
When players use command /tp <x> <y> <z>, they will be dragged back. The reason is Step, Spider or Jump.
Server Version: 1.8.8 PaperSpigot
AntiAura Version: 11.85-3

**Comment by joehot200** [comment]
Does this happen with 100% of teleportations, or are there factors affecting this, such as:

- Server/client lag at the time
- Teleporting to different worlds (e.g. nether)
- The height of the teleportation (is the target height higher than normal height?)

Thanks!

**Comment by Qiuscraft** [comment]
1. TPS: 20, PING: about 60ms
2. teleport to the same world.
3. if the target height is higher than normal height, players will be dragged back. If the target height is normal, players can teleport normally.

**Comment by joehot200** [comment]
Fixed for 11.87. Sorry for the wait!

**Comment by dodofan** [comment]
It was an interesting 100th issue anyway :)
