### ISSUE TITLE
Speed false positives when fast swimming 

### ISSUE THREAD

**Issue by TheTrueColonel** [joehot200/AntiAura#101]
Server Version: Paper #130 1.16.1
AntiAura Version: 11.85-2

When using fast swim in 1.16.1, as an OP, I'm getting dragged back for Flight and Speed. This issue occurs mose commonly when trying to fast swim on the surface, or swimming with a dolphin.

**Comment by ghost** [comment]
Flight is already reported in #83, not sure about Speed though.

**Comment by TheTrueColonel** [comment]
The speed issue is still triggered without head poking out of water.

**Comment by joehot200** [comment]
By "fast swim", do you simply mean the ctrl+w swimming in the game? Flight drag-backs were fixed, so I'm most interested in Speed drag backs. What sort of scenarios do these drag-backs occur in?

**Comment by TheTrueColonel** [comment]
Yeah, that's what I mean by fast swim. I noticed them mainly when swimming with a dolphin, or poking my head out fo the water, though that may be a different issue.

**Comment by joehot200** [comment]
Fixed for 11.87 :).
