### ISSUE TITLE
Elytra flying straight up spider false positive

### ISSUE THREAD

**Issue by ajgeiss0702** [joehot200/AntiAura#112]
Hello,

If a player flys up (doesn't have to be straight up) using an elytra and fireworks when next to blocks, it false flags them for spider.

**Comment by joehot200** [comment]
More info needed:

(Flew up from ground hugging the wall)

![image](https://user-images.githubusercontent.com/6872507/92589658-c9064600-f292-11ea-9514-e8ea18bcdd67.png)

**Comment by joehot200** [comment]
Fixed for 11.92
