### ISSUE TITLE
Soulsand elevator next to fence causes spider false flagging

### ISSUE THREAD

**Issue by ajgeiss0702** [joehot200/AntiAura#113]
When there is a soul sand elevator and fences next to it, it causes a false flag when a player tried to go 

Picture of the elevator:
![image](https://user-images.githubusercontent.com/6259574/89453624-66121400-d714-11ea-84a0-79a0f7380549.png)

**Comment by dodofan** [comment]
Confirmed on 11.86.

**Comment by dodofan** [comment]
Probably resolved in 11.88, as the update note referring to "Fixed a Spider false positive related to water elevators."
