### ISSUE TITLE
A Few Bypasses

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#12]
I found a few bypasses, I'm going to be updating this with a video tomorrow and more info tomorrow

Well, going on an alt fixed pretty much everything, I don't know if this issue report will have to stay open now because I'm going through all the hacks again

**Comment by Jakaboii** [comment]
I'm gonna be making a video later, I just re-tested the checks for now because they weren't detecting my main account yesterday

Bypassed Checks:

AutoBow/FastBow | Settings: https://hatebin.com/qidzjplffu

Map (It also didn't block ChestESP, that just isn't shown in the screenshot I took) | Settings: https://hatebin.com/dqqyarjqmb | Image: https://imgur.com/YNU2kfw

Speed (It's very subtle, so I don't know how hard that should be to detect) | Settings: https://hatebin.com/nqdrahqntm

Phase (Crouching always bypasses, sometimes walking does) YClip (Only down works, I only tested down with a slab so I don't know if a full block is needed or not) | Settings: https://hatebin.com/hakwlggknq

**Comment by Jakaboii** [comment]
OK, here is a video, sorry it took a while
https://www.youtube.com/watch?v=_yHtC4emsIY

**Comment by joehot200** [comment]
Thanks for the report, this looks very useful. I'll have to double-check some of them - for example, it seems strange that Map and TileESP isn't working as intended. However, it'll definitely be something to look into.

**Comment by Jakaboii** [comment]
Alright, thanks
I followed the installation for Xray and stuff correctly, so I'm sure it isn't something wrong on my side
