### ISSUE TITLE
Hitting mobs through slabs triggers occlusion check and killaura hack

### ISSUE THREAD

**Issue by AngieC233** [joehot200/AntiAura#120]
Running Anti Aura v11.86-5 on Paper version git-Paper-133 (MC: 1.16.1) 

Hitting and trying to kill mobs through slabs triggers occlusion check and killaura.  Players got kick for hacking by Occlusion check. Is there a way to patch it?

[Mon, 10. Aug 2020 13:02:16 UTC INFO] [AntiAura] Wolfi_008 Has been detected as hacking! Hack: Killaura. Check: Occlusion. NMS Ping: 80 TPS: 20.0 Notes: Player could not see the SKELETON they were hitting.
[Mon, 10. Aug 2020 13:02:16 UTC INFO] CONSOLE issued server command: /kick Wolfi_008 You were detected for hacking by the Occlusion check!
[17:42]
Farms like the enclosed screenshots
![2020-08-11_17 39 40](https://user-images.githubusercontent.com/32142315/89889412-2790c380-dc04-11ea-93f5-42acdad10816.png)
![2020-08-11_17 39 14](https://user-images.githubusercontent.com/32142315/89889415-28c1f080-dc04-11ea-96e3-220e4cbbf890.png)

**Comment by joehot200** [comment]
Spammed some rays at the issue, please reopen if you encounter any more problems
