### ISSUE TITLE
[API Request] HitCancelledEvent

### ISSUE THREAD

**Issue by coco0325** [joehot200/AntiAura#123]
Triggered when AntiAura wants to cancel a player to deal damage.
Methods:
isCancelled()
setCancelled(bool)
getPlayer()
getEntity()

**Comment by joehot200** [comment]
Added for next update: DamageModifiedEvent

(some checks such as HeadMove will reduce damage, as well as cancelling it outright)

**Comment by ghost** [comment]
11.88 will have a recoded API (in general).
