### ISSUE TITLE
[BUG] Random Error

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#125]
There's this random error that started spamming my console, I'm pretty sure it's when I bypass Occlusion (https://github.com/joehot200/AntiAura/issues/124)

**Comment by Jakaboii** [comment]
Nope, it's not just when I bypass occlusion, but whenever I trigger a check

**Comment by Jakaboii** [comment]
This is the error by the way, forgot to post it lmao https://hatebin.com/hdwjeboiyt

**Comment by joehot200** [comment]
Fixed.

Thanks.
