### ISSUE TITLE
Potionsaver

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#13]
Most of the time when a player joins, they are on Lunar Client if that makes sense

This is their log

The player DrippyPlaysMC failed the PotionSaver check. The PotionSaver check detected the person as using the PotionSaver hack.
He/She hit more than the threshold at 2020/04/04 21:39:47.
He/She had a NMS ping of 77
The server TPS was at: 20.0
He/She had the ABSORPTION 0 potion effect!

If this is a false kick,
It is recommended you go into the configuration and change the settings.
Contact me if you need any help with that.
Notes: Player sent 0 packets in the last second!

**Comment by joehot200** [comment]
Hi,

What is the 'lunar client'? Does the issue only occur with the lunar client, or does it occur with the normal client too?

Also, does the issue occur if the player is already online? (For example, enable antiaura when player is already online)

Thanks
Joe

**Comment by Jakaboii** [comment]
[Lunar Client](https://www.lunarclient.com) is a Minecraft client with mods & client-side anticheat that boosts FPS

It only happens on Lunar Client & doesn't happen when the player is already online, only most of the time when they join

It could either just be the way Lunar Client changes vanilla Minecraft (like some other clients) and AntiAura doesn't like it, since AntiCheats usually don't like the way some clients change vanilla

**Comment by joehot200** [comment]
Interesting. I'll leave this as high-priority and take a look when I can.

As for a fix temporarily, I would recommend increasing the Threshold on PotionSaver. By default, it is 5, however you can try a value of 10 or even 15 to see if that helps. It should give the player more time after joining to be sending packets correctly.

Give it a go and let me know how it goes! As I say though, even if raising the Threshold works, I'll take a proper look at this some time.

**Comment by Jakaboii** [comment]
OK, thanks a lot!

**Comment by joehot200** [comment]
> OK, thanks a lot!

Could you let me know if increasing the Threshold solves your issue? It would be helpful to know if this is the case for when I go about fixing the bug. Thanks!

**Comment by Jakaboii** [comment]
I increased it to 10 and the issue hasn't happened since

I haven't tested with different thresholds yet

**Comment by Jakaboii** [comment]
Beforehand it was when the user connected to server FROM the hub, now it happened when they were connected TO the hub

This time though, they were connecting on a hacked client (they might have had some hacks enabled, but it kicked them for the same reason as it did with the player on Lunar Client)

I lowered the value to 8 on both servers & did some brief testing & it works fine

**Comment by Jakaboii** [comment]
Nevermind, I had to increase the value back to 10 on the hub, KitPvP works fine on 8

**Comment by joehot200** [comment]
Thank you @Jakaboii, that's useful to know. Still working on it though, sorry for the wait.

**Comment by Jakaboii** [comment]
It's fine, had to increase the value to 12 now on the Hub again

I'm gonna try and ask what client they were using if that helps

**Comment by Jakaboii** [comment]
They were using Flux B14 and didn't have any hacks enabled

**Comment by Jakaboii** [comment]
OK potion saver is really unstable now, I'm just going to increase it to 100 or something as it's still banning people when they try to connect to the hub

Could it be that I'm using Flamecord as a proxy?

**Comment by Jakaboii** [comment]
It must be that I'm using Flamecord or something, they just joined on vanilla minecraft and got banned

Edit: They were using Badlion client

I'll restart the proxy & everything and see if that resolves the issue

**Comment by Jakaboii** [comment]
OK there's something seriously wrong

At 100 it still bans them, I've advancedconfig enabled and I'm going to set the value in the normal config to -1 and see if that makes a difference

**Comment by Jakaboii** [comment]
Think it may have been that I had the value in config.yml still enabled

This could maybe be looked at?

Edit: This isn't why, on KitPvP the value is 4 in config.yml but the value in advanced_config.yml is still being used

I'm really confused..

**Comment by Jakaboii** [comment]
OK, I have disabled the PotionSaver check on all servers as it's starting to ban on KitPvP too

Hopefully this can be fixed in a future update and sorry for this confusing github report!

**Comment by dodofan** [comment]
https://pastebin.com/WXNpBNVp

Occurred after I tried joining a server. I glitched joining in and AntiAura kept trying to kick me (replaced with /tell because test server). Not sure if this is just unavoidable because of the situation, though.

**Comment by joehot200** [comment]
I believe this has now been solved. Please could you reopen if you find any issues.

Thanks!
