### ISSUE TITLE
Errors in AntiAura 11.88

### ISSUE THREAD

**Issue by coco0325** [joehot200/AntiAura#131]
https://pastebin.com/TsQQ6mZp
https://pastebin.com/X4E0PepZ

Also setCancelled(true) in DamageModifiedEvent does not work.

Paper 1.16.3

**Comment by joehot200** [comment]
When do these errors occur? I could not duplicate them by walking around or hitting a few entities.

What behaviour are you expecting by cancelling the DamageModifiedEvent?

**Comment by coco0325** [comment]
This (https://pastebin.com/TsQQ6mZp) occured when I placed a smithing table.
And I don't know how this (https://pastebin.com/X4E0PepZ) occured.

I expect the it will deal the same damage by cancelling the event.

**Comment by coco0325** [comment]
@joehot200

**Comment by joehot200** [comment]
I'm still not able to duplicate it, which is definitely frustrating. The problems are occuring from Bedrock/Floodgate compatibility, do you have either of those installed? If not then they may be activating incorrectly, but why on your server and not mine?

I'll try to keep testing.

**Comment by coco0325** [comment]
What about DamageModifiedEvent? Can you duplicate it?

**Comment by AngieC233** [comment]
Running Paper 1.16.3 and have these errors too spamming on console.  Not sure if its the same issues...

https://pastebin.com/fGN0NFRZ

**Comment by joehot200** [comment]
@AngieC233 @coco0325 I have a hotfix tonight that I **hope** will solve the problem. I'm really sorry for the wait.

**Comment by joehot200** [comment]
I uploaded a hotfix that attempts to solve these problems, please let me know, and **if** errors still exist please send me the **new errors** from 11.88-1. Thank you!
