### ISSUE TITLE
Memory Leak Suspection

### ISSUE THREAD

**Issue by coco0325** [joehot200/AntiAura#134]
After I upgraded AntiAura to 11.88, the RAM usage of the server increased severely and it caused my server out of memory then crashed.
I used Eclipse memory analyzer to analyze the heapdump, and I found that AntiAura has a unnormal RAM usage.

![image](https://user-images.githubusercontent.com/22321097/94156571-cf133e00-feb2-11ea-9296-607df1e956d1.png)

**Comment by Jakaboii** [comment]
Do you have `All.StopCrashes` enabled in the advanced config? It could cause slight memory leaks but nothing like this I'm pretty sure..

**Comment by coco0325** [comment]
@Jakaboii No, I didn't.

**Comment by joehot200** [comment]
Could you confirm it's definitely 11.88-1 that this report came from?

Also, how accurate is your checker? Is it specifying joehot200.Y because it calls other classes, or is it specifying that class because it has lists (e.g. an ArrayList) in that specific class that are causing leaks?

**Comment by joehot200** [comment]
I *believe* that I have solved the memory leak. When 11.89 comes out, please test it again :)

**Comment by joehot200** [comment]
Reopening as dev builds seem to have leaks too.

@coco0325 Could you please get me a heap dump of your server when the RAM is being taken up by AntiAura? You can use https://www.spigotmc.org/resources/heapdump.1433/ to print out a heap dump.

Thanks!

(archive the .hprof into a .zip, it'll make it about a quarter of the size)

**Comment by coco0325** [comment]
Okay. Give me some time.

**Comment by joehot200** [comment]
> Okay. Give me some time.

Thank you :)

**Comment by coco0325** [comment]
Btw, I got some errors here.
https://pastebin.com/HF8jq3Eg

**Comment by coco0325** [comment]
@joehot200 
https://drive.google.com/file/d/1AZvYhWEXJ58lwxFUT8Bq6qhuoIh5Qn7j/view?usp=sharing
Here you are.

**Comment by joehot200** [comment]
I am keeping this open after 11.90 because there are still further checks I need to do on @coco0325's memory dump to ensure all leaks are definitely quashed, despite having fixed some memory leaks for 11.90-1.

**Comment by coco0325** [comment]
https://pastebin.com/rSQK8s23

**Comment by coco0325** [comment]
It seems that there still are some leaks.
https://pastebin.com/rSQK8s23

**Comment by joehot200** [comment]
> It seems that there still are some leaks.
> https://pastebin.com/rSQK8s23

How do you know the crash is from a memory error?

**Comment by coco0325** [comment]
The crash is after the installation of latest Antiaura.

**Comment by coco0325** [comment]
I believe there are still several memory leaks.
AntiAura 11.96
Purpur 1.16.5
Additional infomation: I have plugin use to cancel specific type of viovation events and drag back events.

![image](https://user-images.githubusercontent.com/22321097/126642772-31b71cf4-b313-4ac1-b761-9a727233bdc6.png)
![image](https://user-images.githubusercontent.com/22321097/126643737-2b2a732e-0245-4ef8-a3c4-6e64a2bcd1bd.png)

**Comment by coco0325** [comment]
![image](https://user-images.githubusercontent.com/22321097/126940933-25a909e6-f025-4d67-b8d4-5746a66e6843.png)
![image](https://user-images.githubusercontent.com/22321097/126940992-288f2c57-cb17-46d9-a4da-381f15f2e8cb.png)

I don't know if the leak is cause by this new error.
https://pastebin.com/HvY8RvwS

**Comment by coco0325** [comment]
![image](https://user-images.githubusercontent.com/22321097/127078669-76a36324-54be-451a-b70e-dbf3f40ff73d.png)
![image](https://user-images.githubusercontent.com/22321097/127078693-62f2557d-d506-4980-925c-d66ecc74a97a.png)

AntiAura 11.97-1

**Comment by coco0325** [comment]
![image](https://user-images.githubusercontent.com/22321097/128677374-b6f0f47b-a16c-4f85-b20a-9a1fc1b6df20.png)
AntiAura 11.98

**Comment by coco0325** [comment]
The HashSet "aF" caused the memory leak.

**Comment by joehot200** [comment]
@coco0325 Forgive me for being forgetful but did I ever get around to fixing this?

**Comment by coco0325** [comment]
This is already fixed.
