### ISSUE TITLE
[FP] Reach

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#137]
## Troubleshooting Information

**AntiAura version:** 11.88-1

**Server version:** Paper 1.8.8

**Client version:** 1.8.9

## Proof & Config

**Screenshot (or a video recording):** https://www.youtube.com/watch?v=ZDgccoxB-BY

**Check(s) config (if applicable):** https://hatebin.com/oukgyjndcv

## Issue Information

**Steps to reproduce:** In the video

**Additional Information:** I've no idea why it flags, when you can see in the video that I only reached 2 blocks but AntiAura thinks I reached 4.1 blocks instead and in the config I have the MaxReach set to 3.0

**Comment by joehot200** [comment]
**Fixed for 11.99**. The Reach check has been removed and replaced by the ImpossibleHit check.
