### ISSUE TITLE
11.72: False flagging with Essentials /speed command?

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#14]
**Screenshot (or a video recording):** https://youtu.be/V8udmWAFwFw

**AntiAura version:** 11.72

**Server version:** CraftBukkit version git-Spigot-56f8471-3e3818b (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Minecraft version:** 1.14.4 OptiFine

**Hacked client:** None (vanilla)

**Check(s) config (if applicable):**
Included in the video. 

**Detailed description of the issue:**
Setting your fly speed using /speed 10 drags you back when used.

**Additional details:**
None.

**Comment by joehot200** [comment]
Cheers, appreciate the report. Put it as high priority just because it's easy to fix, so I might as well get it out the way.

**Comment by dodofan** [comment]
@joehot200 Just an update - this can also flag Flight too in 11.76. I can provide a video if necessary.

**Comment by joehot200** [comment]
Cannot duplicate on 11.8302

**Comment by joehot200** [comment]
Fixed for 11.84.
