### ISSUE TITLE
Reach acts weird when you are on top of the enemy vs in front of them

### ISSUE THREAD

**Issue by personinblack** [joehot200/AntiAura#140]
Consider Situation A here:
![2020-09-30-203758_1920x1080_scrot](https://user-images.githubusercontent.com/24732321/94720212-d9bf4e80-035c-11eb-860c-fd50d49a4b1e.png)
I am 3 blocks above the ground and can hit the skeleton fine.

Then Situation B here:
![2020-09-30-204045_1920x1080_scrot](https://user-images.githubusercontent.com/24732321/94720500-3ae72200-035d-11eb-9b86-86a2fafb13e2.png)
I am like 3.3 blocks away from the skeleton and I can hit it fine.

Now when I set `MaxReach` to `2.9` Situation B is okay but Situation A generates false positive. Setting the value to `3.3` clears that false positive but make it more lenient in Situation B. It acts differently in both situations while it shouldn't.

**Comment by joehot200** [comment]
@personinblack This should now be fixed, as Reach was removed and ImpossibleHit was added. Would you be able to test and confirm? ;o
