### ISSUE TITLE
Dolphin's Grace false positive

### ISSUE THREAD

**Issue by personinblack** [joehot200/AntiAura#144]
In issue #119 this is told to be fixed but it is still happening to me. I get constant drag backs near dolphins (can't move up, down, forward). `DragBackThreshold && SwimMult: 9999` does not disable drag backs under water so I had to disable the check completely.

![2020-09-30-232846_1920x1080_scrot](https://user-images.githubusercontent.com/24732321/94736318-b43e3f00-0374-11eb-8003-4aab600c8af6.png)

**Comment by AngieC233** [comment]
Wondering will this be fixed as players are complaining they get constantly dragged back near dolphin, they can't even move and easily drowned due to this issue
Updated to the latest version of Anti Aura 11.91-1 doesn't help. Running latest paper version

**Comment by dodofan** [comment]
Don't fret. Developmental builds for 11.92 currently list Dolphin's Grace at this time, so it should hopefully solve any bugs related to this issue.

**Comment by joehot200** [comment]
Believed fixed for 11.92

**Comment by cades66** [comment]
Hi - I'm having the same issue on my server, players are getting flagged for hacks and kicked when they're on their sea base with dolphins around.
