### ISSUE TITLE
Trident with Riptide false positives

### ISSUE THREAD

**Issue by personinblack** [joehot200/AntiAura#147]
Using a Trident with Riptide enchantment to move high up out of water makes the server think you are still in water and damages you run out of air. Only way to fix this is reconnecting which spawns you at where you were before using Trident. No errors or any clue at console or anywhere else I can find.

**Comment by joehot200** [comment]
I believe the Teleport check is causing the problem.

**Comment by joehot200** [comment]
Believe fixed for 11.82
