### ISSUE TITLE
One Task takes very much performance.

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#15]
One Task use very much performance. I just don't know which to deactivate it 'til you fix it.
https://timings.aikar.co/?id=ae1cd8b5a3524ab5bed4dea4dcce0d86#timings

**Comment by joehot200** [comment]
(Note to self: Also exists at https://github.com/joehot200/AntiAura/issues/1)

I believe it is the Map check. I have got fixing it as one of my highest priorities. I believe there may also be an option to use the old ray checking, though you'll need to test how effective (or working) it is.

Thanks!
Joe

**Comment by joehot200** [comment]
Map is now async
