### ISSUE TITLE
Experiencing console errors related to zombie_striker and BlockPlaceEvent

### ISSUE THREAD

**Issue by dylanjkl** [joehot200/AntiAura#150]
I'm currently experiencing these issues within the console, they reproduce over and over again uncontrollably in the console.
![image](https://user-images.githubusercontent.com/25552125/102451328-26e3c000-4030-11eb-93cb-2d3b50ec79ab.png)

**Comment by joehot200** [comment]
Attempted to fix in 11.92 but could not duplicate

Are you able to give any more info?
