### ISSUE TITLE
Dolphins' Grace causing Speed false positives

### ISSUE THREAD

**Issue by cades66** [joehot200/AntiAura#154]
Hi, I have a server with default AntiAura configs except that speed is a 4 instead of the default 5, however Dolphins' Grace is getting multiple flags and kicking / banning my players.

Can you help out?
![javaw_K2YUGpyhSZ](https://user-images.githubusercontent.com/57970060/107548044-c9817080-6b93-11eb-8d53-20c69c324d3a.png)

**Comment by joehot200** [comment]
I **believe** this is fixed for 11.93. Was Dolphin's grace also combined with Depth Strider?

I've made changes to dolphin's grace which I'm hoping should solve the issue but please let me know if not after 11.93 releases.
