### ISSUE TITLE
Exception while executing task 31

### ISSUE THREAD

**Issue by TimGraham777** [joehot200/AntiAura#156]
Console keeps getting filled up with this warning. Is there a fix for this?

13.02 08:19:42 [Server] Craft Scheduler Thread - 166/WARN Plugin AntiAura v11.92-1 generated an exception while executing task 31
13.02 08:19:42 [Server] INFO java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getSectionPositions()Lcom/comphenix/protocol/reflect/StructureModifier;
13.02 08:19:42 [Server] INFO at AntiAuraAPI.d.a(d.java:49) ~[?:?]
13.02 08:19:42 [Server] INFO at joehot200.G.a(G.java:322) ~[?:?]
13.02 08:19:42 [Server] INFO at joehot200.aR.run(aR.java:111) ~[?:?]
13.02 08:19:42 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot_1.16.5.jar:3007-Spigot-cd23533-a82b212]
13.02 08:19:42 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot_1.16.5.jar:3007-Spigot-cd23533-a82b212]
13.02 08:19:42 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
13.02 08:19:42 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]

**Comment by joehot200** [comment]
I believe you need to update ProtocolLib, maybe I'll make it more explicit in the error message, a lot of people seem to encounter this.

**Comment by joehot200** [comment]
**Fixed**: Added additional warnings to inform users if they are using the wrong ProtocolLib version

**Comment by TimGraham777** [comment]
That fixed it. Thank you!
