### ISSUE TITLE
Commands not registered with Bukkit - AntiAura commands working, but Bukkit reporting unknown command,

### ISSUE THREAD

**Issue by cades66** [joehot200/AntiAura#157]
I think it's pretty self explanatory. Running almost any AntiAura command (such as /aver or /anotify) will have the antiaura message sent AS WELL AS a bukkit error.

![image](https://user-images.githubusercontent.com/57970060/108254355-863d7980-7120-11eb-9f2d-50c7b1ccfe20.png)

**Comment by cades66** [comment]
It also appears that Bukkit does not have ANY of AntiAura's commands registered (No tab completion).

**Comment by joehot200** [comment]
Was intending to fix in 11.93 but didn't have time, hoping to fix for 11.94.

**Comment by ghost** [comment]
@cayoten In terms of your tab completion issue, it should now be an option under the "Specifics" section within the advanced configuration as of 11.93.

**Comment by cades66** [comment]
Got it. Thanks!

**Comment by joehot200** [comment]
Fixed, added some tab completion too.
