### ISSUE TITLE
1.17/1.17.1 critical bug with shulkerbox

### ISSUE THREAD

**Issue by MelonHell** [joehot200/AntiAura#163]
how to repeat:
place a new shulker
put items in it
breaking the shulker
In the inventory there is a shulker with items
place shulker with items
there was an empty shulker
open it and see that it is really empty

This bug is not present on 1.16.5!!!

info:
AntiAura v11.96 + ProtocolLib build 530
tested minecraft versions:
1.17.1 Airplane (build 45)
1.17.1 Purpur (build 1262)
1.17 Paper (build 71)

**Comment by joehot200** [comment]
Fixed for the next update. Thank you for the bug report, I don't think I would have found this otherwise :)
