### ISSUE TITLE
AntiAura Disables Elytra While Flying

### ISSUE THREAD

**Issue by coco0325** [joehot200/AntiAura#164]
I found that the plugin forces players to disable elytra while they are flying. I hope there's a option to turn off this.

Purpur 1.16.5
AntiAura 11.96

p.s. No drag back or violation detected on the flying player.

**Comment by joehot200** [comment]
I believe I fixed this for 11.98, could you confirm?

**Comment by coco0325** [comment]
Unfortunately, it hasn't been fixed yet.

**Comment by joehot200** [comment]
Do you know how I'd go about duplicating this?

**Comment by coco0325** [comment]
Try player.setSpeed(player.getSpeed * 3.0) while player using elytra.

**Comment by joehot200** [comment]
Just tried the walk speed but couldnt find an issue. Which speed are you changing, or are you setting the player velocity directly??

**Comment by coco0325** [comment]
Changing player's velocity directly.

**Comment by joehot200** [comment]
Fixed. Only took me 1 year too ;o
