### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by coco0325** [joehot200/AntiAura#168]
Is there any API changes? I can't cancel the violations through API.

**Comment by joehot200** [comment]
I am not aware of any, which violation are you attempting to cancel?

(Edit: Didn`t mean to close the issue that was an accident)

**Comment by coco0325** [comment]
Many of them. I have a plugin to cancel the certain violations in some circumstances, and I noticed that it stopped working after I upgraded AntiAura from 12.0 to 12.06.

**Comment by joehot200** [comment]
Ah, so you are saying that the ViolationEvent is no longer cancellable? I will look into this!

**Comment by joehot200** [comment]
Looks like you are correct. I have now fixed the issue so that the API is working, but please let me know if you encounter any issues (for example if you encounter false positives shortly after cancelling a violation).

**Comment by coco0325** [comment]
Is the fixed version released?
