### ISSUE TITLE
Jump Dragback

### ISSUE THREAD

**Issue by coco0325** [joehot200/AntiAura#169]
Players with the jump potion effect will be dragged back when jumping.

**Comment by coco0325** [comment]
Antiaura 12.14-1
PaperSpigot 1.17.1

**Comment by coco0325** [comment]
Also, DragBackEvent is not working. I am not informed of any drag backs since I upgrade to 12.14-1.

**Comment by Michael-A-Sloan** [comment]
This also happens when there is an effect from a beacon for the jump too.

**Comment by joehot200** [comment]
This has been fixed in the just-released 11.14-2 update. Sorry for the wait!
