### ISSUE TITLE
Found issue with entities becoming invisible with AA loaded on the server 

### ISSUE THREAD

**Issue by Michael-A-Sloan** [joehot200/AntiAura#171]
So I have just found an issue where Entities like MOBS, Players, Armor Stands and other things being invisible when the AA plugin is loaded on the server.  

At first I didn't think it was this plugin doing it but I ran a few tests where I took the plugin completely off the server and everything became visible again.

Server Version: Paper 1.19 most updated

**Comment by Michael-A-Sloan** [comment]
I have also changed all the map ray settings to see if it would fix it and no setting works.

**Comment by joehot200** [comment]
I'll be getting onto this. 1.19 issue only afaik. Apologies for the wait.

**Comment by Michael-A-Sloan** [comment]
thanks for the info and help here.

**Comment by joehot200** [comment]
This has been fixed in the just-released 11.14-2 update. Sorry for the wait!
