### ISSUE TITLE
11.72: False flagging with breaking blocks

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#18]
**Screenshot (or a video recording):** 
DMs with @joehot200, and additional footage at https://youtu.be/YA1X_LI1iJc

**AntiAura version:** 11.72 (present in 11.76 also)

**Server version:** Paper 1.15.2

**Minecraft version:** 1.15.2

(This issue was opened to ensure that all the issues are fixed by getting them in one place)

**Detailed Description:**
Standing in a certain position and trying to break blocks will eventually get you detected for Nuker/FastHand/GhostHand. Most likely this occurs with anything that you can break quickly, such as a sign in creative.

**Comment by joehot200** [comment]
Believed fixed in 11.85. Please test at some point and reopen if not solved.
