### ISSUE TITLE
FastEat (NoSlowDown) false positive

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#21]
When someone eat's a golden apple in mid air, it false bans for FastEat/NoSlowDown

[AntiAura] ImnotJesusChrist Has been detected as hacking! Hack: NoSlowdown. Check: FastEat. NMS Ping: 59 TPS: 19.9990234375 Notes: Last distance travelled: 1.2700074151238494
> [12:26:12 INFO]: 2020/04/26 12:26:12

**Comment by joehot200** [comment]
Currently cannot duplicate, please can I have more information?

I tried:

- Start eating, jump off 3 blocks high
- Same with 5 blocks
- Same with like, 50 blocks
- Jump off, start eating, land when eaten

**Comment by Jakaboii** [comment]
I've since changed the settings and I no longer have them

If I run into this issue again I'll make a new report
