### ISSUE TITLE
Step false positive

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#23]
Sometimes step drags players back, I don't know what the player was doing but it keeps happening sometimes

Step settings: https://hatebin.com/szacsallkf

**Comment by Jakaboii** [comment]
I have temporarily disabled step as it kept on false flagging

**Comment by joehot200** [comment]
Step's TPS accounting has been greatly improved. May not seem like much, however even if a command or something froze your server for a tick or two, false positives could occur, and this could happen even if /tps averages out at 20 TPS.

Please make a new issue if false positives still occur after the 11.81 update.

Cheers!
