### ISSUE TITLE
Latest AntiAura v11.76 spamming errors and eventually crashed server

### ISSUE THREAD

**Issue by AngieC233** [joehot200/AntiAura#25]
Running Paper version git-Paper-228 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Anti Aura v11.76

After uploading the latest version to the server, the console was spamming with the errors enclosed in the pastebin, eventually crashed the server.  

I downgraded to v11.72, however for some reasons players are only able to place only several blocks, then they are unable to place any more blocks and when trying to place anything, it just disappears within like half of a second.

Wondering if the advanceconfig.yml auto reset when we downgrade a version as it does updates when upgrade to the latest version.  Not sure if it could cause issue if the config doesn't update.

Remove Antiaura for now till it's resolved.

https://pastebin.com/kbrMgCiE

**Comment by joehot200** [comment]
Hi,

Please reset your configuration on 11.76, or manually add SetDataToo and UseBlockData to TileESP:
https://pastebin.com/6repGUbm

You're right that it's a configuration issue. With hindsight, I should have forced a configuration reset.

**Comment by AngieC233** [comment]
Ah okay, thank you.  I'll upload the latest version again and reset the config_advance.  I think it's much better to forced configuration reset if there are changes in the config as most people probably don't know they need to reset their configuration with the missing entries.  Otherwise it will cause issues like what we have seen.

**Comment by joehot200** [comment]
Next update will force a configuration reset

**Comment by AngieC233** [comment]
Thank you.  It is possible only to have only the new configuration input reset for that particular check that was changed and not the whole config.yml, advanceconfig file if you know what I meant?
