### ISSUE TITLE
Streamline configuration settings + toggleable checks 

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#27]
**Suggestion:** ~~Streamline the configurable settings in the two configurations. In the example below, you can see the FastEat options for config and config_advanced.yml are exactly the same, but which one takes precedence over the other? One would assume the advanced configuration, but can you really know?~~ (FastEat resolved in 11.79) 
- **PRESENT in 11.81:** ENABLED option exists in basic/advanced configuration in the following checks: Speed, FastPlace, Teleport, Phase, MorePackets, PotionSaver (this can lead to unintended consequences, such as one disabling it in advanced config expecting it to override basic)
- **Additionally,** some checks don't have enable/disable options.
- Removing the text before the `Enabled` values of each check might be worth doing (shouldn't take too long I should think). I think most people know what "Enabled" means.

**Examples:**
FastEat options in config.yml and config_advanced.yml:
config.yml:
#Blocks players from eating food faster than normal.
FastEat:
  #Do you want to block hacked clients from being able to eat food quicker than normal?
  Enabled: true
  #The time, in seconds, that a player can consume food after last having consumed food.
  Time: 1.5

config_advanced.yml:
#Blocks players from eating food faster than normal.
FastEat:
  #Do you want to block hacked clients from being able to eat food quicker than normal?
  Enabled: true
  #The time, in seconds, that a player can consume food after last having consumed food.
  Time: 1.5

**Comment by joehot200** [comment]
Fixed for 11.95 (removed Enabled from advanced config)
