### ISSUE TITLE
11.72: Non-full blocks over water - NoFall bug

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#3]
**Issue:** NoFall false positives when water is placed under non-full blocks that have been placed over a full block.

**Other Notes:** Flight, and DistanceSpoof false positives have also been occasionally reported.

**Config:** Expressed in the provided media.

**Documentation:** https://youtu.be/dgAsLDTumUY
Credit: FieryFires

**Additional details:**
Occurs with cacti that naturally generates on hanging sand.

**Comment by joehot200** [comment]
Fixed for 11.95
