### ISSUE TITLE
AntiAura notification system

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#30]
**Suggestion:** Create a notification system with relevant permissions and commands. For example:

Player gets detected by AntiAura, and execute command would be something like "/atell" (/anotify doesn't work obviously) or something similar to AAC's, "/astaffnotify." 

This allows specific people to receive AntiAura kick messages without having to op players using systems like helpop or others.

**Comment by joehot200** [comment]
This was done last update with /aamodnotify
