### ISSUE TITLE
11.76: Lagback when disabling and reenabling Jump

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#31]
**Screenshot (or a video recording):** https://youtu.be/h8cA69glyPo

**AntiAura version:** 11.76

**Server version:** CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)

**Minecraft version:** 1.8.9 OptiFine

**Hacked client:** None

**Check(s) config (if applicable):**

From config_advanced.yml (see note in additional details)
Jump:
  #How much further than the maximum distance should AntiAura allow players to jump?
  #Useful for providing leniency in cases of lag.
  #Advanced config only.
  LeniencyInBlocks: 0.5
  #How much the players' Jump violation level goes down after a legitimate jump.
  #Advanced config only.
  SafeJumpDecrease: 0.5
  #The threshold the players' Jump violation level must reach for them to be detected for Jump.
  #Advanced config only.
  Threshold: 8
  #If the threshold is above the DragBackThreshold, players are dragged back when jumping too far.
  #Setting this higher than 0 can, of course, allow players to jump illigitimately far until they reach the DragBackThreshold.
  DragBackThreshold: 0
  #Command to execute when Jump is detected.
  JumpCommand: # 

**Detailed description of the issue:**
Disabling Jump, moving forward a specific amount (probably adjustable in config but still a bug), reenabling it and then moving will cause you to lagback to the position where you disabled it. 

**Additional details:**
From what I can tell, I don't think this is a configuration issue. Also, on another server of mine with the advanced config, it still lagsback (the current video uses the default config.yml with a strictness of 6).

**Comment by joehot200** [comment]
Fixed for 11.95
