### ISSUE TITLE
11.76: Underwater Speed Lagback Bug

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#32]
**Screenshot (or a video recording):** https://youtu.be/85r5O0Ah6SM

**AntiAura version:** 11.76

**Server version:** Paper version git-Paper-228 (MC: 1.15.2)

**Minecraft version:** 1.15.2 OptiFine

**Hacked client:** None

**Check(s) config (if applicable):**
Provided in the video.

**Detailed description of the issue:**
Swimming down and pressing shift will sometimes lag you back for Speed, causing for an annoying experience and sometimes dangerous if you're running out of air.

**Additional details:**
None.

**Comment by joehot200** [comment]
Fixed for 11.81

**Comment by joehot200** [comment]
Fixed for 11.81
