### ISSUE TITLE
11.76: Dragged down when standing on glass pane

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#33]
**Screenshot (or a video recording):** https://youtu.be/GhMGBK1_YFQ

**AntiAura version:** 11.76

**Server version:** Paper 1.15.2

**Minecraft version:** 1.15.2 OptiFine

**Hacked client:** None

**Check(s) config (if applicable):**
Provided in the video.

**Detailed description of the issue:**
See video.

**Additional details:**
None.

**Comment by joehot200** [comment]
Fixed for 11.81
