### ISSUE TITLE
11.79: NoFall DistanceSpoof False Positive when falling through water

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#38]
**Screenshot (or a video recording):** https://youtu.be/oirQ7UxfSyk

**AntiAura version:** 11.79

**Server version:** Paper version git-Paper-282 (MC: 1.15.2)

**Minecraft version:** 1.15.2 (appears on 1.8 as well)

**Hacked client:** None

**Check(s) config (if applicable):**
Provided in the video.

**Detailed description of the issue:**
Steps to reproduce:
1) Build as seen in video.
2) Jump up and then fall. 
NOTE: Jumping may not be needed if you build higher, I am unsure.

**Additional details:**
Credit to Jakaboii for originally pointing this out.

**Comment by joehot200** [comment]
Currently cannot duplicate this. Is there any more information you can give me?

I tried with Strictness at -1 and LeniencyTime at 0, which should make it as strict as possible.

**Comment by dodofan** [comment]
I assume this is resolved in the 11.81 development build? @joehot200

**Comment by joehot200** [comment]
> I assume this is resolved in the 11.81 development build? @joehot200

Read the close comment: "cannot duplicate this".

**Comment by ghost** [comment]
What more information do you want?

**Comment by joehot200** [comment]
> What more information do you want?

Well I copied the actions in the video, and could not find a bug. So, information that lets me duplicate the bug, if it still exists?

**Comment by dodofan** [comment]
I don't code the plugin. I don't know what information would be helpful for duplication besides what I have already shown. Have you tried slightly modifying your replication? Maybe building higher or not jumping?
