### ISSUE TITLE
Speed Check

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#4]
The speed check is very unstable and false flags a lot

Even after messing with the settings, just running around false flags sometimes

Hopefully this can be fixed in a future update

**Comment by joehot200** [comment]
Hi,

Could you please give me more information about the issue? If I wanted to view the problem myself, how would I go about it?

What settings have you "messed with"?

Thanks
Joe

**Comment by Jakaboii** [comment]
You literally just have to run around & it false flags

I use PvPLounge and I know that sometimes changes mechanics, but I don't think it changes movement mechanics

And I lowered some settings in the advanced config & have speed in the normal config set to -1 so it uses it 

Here are my settings: https://hatebin.com/fujqfsjpnn

**Comment by Jakaboii** [comment]
OK

Sometimes with the speed check I might just be running around my paper 1.8.8 server using the latest AntiAura version with the configuration settings above

After running around for maybe 20-30 minutes it deals damage to me, so I check console & it says I was speeding

It'd be nice if you had formats to follow & specific tags we choose when making github reports too :)

**Comment by joehot200** [comment]
@Jakaboii Alright, I'll take a look into it. Question about SpeedLeniency, was your intention to use 0.10 for SpeedLeniency rather than the default 0.20? I'm surprised you made it stricter if you're encountering false positives.

Anyway, I'll give this a priority and take a look when I have time. Cheers!

**Comment by Jakaboii** [comment]
Oh. I didn't know that lowering it makes it stricter, I'll change it to .30 or .25 and see if that makes a difference

Thanks

**Comment by Jakaboii** [comment]
It seems to be fixed.. I changed it and used it for a while and it seems fine now

I'll reply to this or make a new issue if anything else falses

**Comment by dodofan** [comment]
Just a note: This is probably tied in to the LowerAmount issue (see #62), so it would've _hopefully_ been fixed by then anyway.
