### ISSUE TITLE
[FP] Speed

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#40]
## Troubleshooting Information

**AntiAura version:** 11.79

**Server version:** Paper 1.8.8

**Client version:** 1.8.9

**Hacked client:** LiquidBounce

## Proof & Config

**Screenshot (or a video recording):** https://www.youtube.com/watch?v=64I_2JN96Hk

**Check(s) config (if applicable):** Default

## Issue Information

**Detailed description of the issue:** When running and spam jumping on packed ice or normal ice with trapdoors above your head, it flags for Speed

**Steps to reproduce:** Run and spam jump on ice or packed ice with trapdoors above you

**Additional Information:** I didn't have any hacks on while testing this

**Comment by Jakaboii** [comment]
Also happens on normal ground

https://www.youtube.com/watch?v=vqJT0lI-cXI

**Comment by joehot200** [comment]
Fixed.
