### ISSUE TITLE
[BYPASS] LiquidWalk (Jesus)

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#41]
## Troubleshooting Information

**AntiAura version:** 11.79

**Server version:** Paper 1.8.8

**Client version:** 1.8.9

**Hacked client:** LiquidBounce

## Proof & Config

**Screenshot (or a video recording):** https://www.youtube.com/watch?v=xlVMwGDivng

**Check(s) config (if applicable):** Default

## Issue Information

**Detailed description of the issue:** Use LiquidWalk hacks on LiquidBounce, all hacks bypass

**Steps to reproduce:** Use LiquidWalk hacks on LiquidBounce, all hacks bypass

**Additional Information:**

**Comment by ghost** [comment]
Duplicated by #17
