### ISSUE TITLE
11.79: Spider, Flight, and DistanceSpoof False Positive when going through kelp

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#46]
**Screenshot (or a video recording):** https://youtu.be/oHV-rA7gwkc

**AntiAura version:** 11.79

**Server version:** Paper 1.15.2

**Minecraft version:** 1.15.2

**Hacked client:** None

**Check(s) config (if applicable):**
Provided in the video.

**Detailed description of the issue:**
Steps to reproduce are shown in the video.

**Additional details:**
This is especially annoying if you're trying to prepare a water elevator using bubble columns (which, actually, have issues of their own that I will upload soon).

**Comment by joehot200** [comment]
Same bug as #47 related to waterlogged blocks.

**Comment by joehot200** [comment]
Fixed for 11.81

Ugh, why does Kelp contain water but isn't "waterlogged".
