### ISSUE TITLE
Flight not blocking Jesus correctly

### ISSUE THREAD

**Issue by joehot200** [joehot200/AntiAura#48]
Flight won't block Jesus unless max height off ground is really low.

**Comment by dodofan** [comment]
I'd like to comment that setting MaxHeight to 0.01 still does not block Jesus **whatsoever.** Here's my current configuration:

#Block flight hacks?
Flight:
  #Use client ground data to make flight detection more strict?
  #IT IS HIGHLY RECOMMENDED YOU ENABLE THIS FOR SERVERS LIKE SKYWARS, PARKOUR, ETC.
  StrictMode: true
  #How many times must the person be detected as flying to be detected?
  #Advanced config only.
  Threshold: 5
  #How many times must the person be detected as flying to be dragged back?
  #Increasing this above 0 will allow players to fly illegitimately for a short amount of time.
  DragBackThreshold: 0
  #When the player is detected to be doing legitimate activities, how much should the Threshold be lowered?
  #Advanced config only.
  LowerAmount: 1.0
  #This value is automatically added onto the MaxDistancePerSecond of a player if he has a jump potion.
  #If this was at 2, the jump height for a player with Jump II would be 6 blocks off the ground.
  ValuePerPotionLevel: 2
  #The maximum height a player can be off the ground to be counted as in the air?
  #Advanced config only.
  MaxHeightOffGround: 0.01
  #How long should the player be allowed to not be standing on a block without going down significantly?
  #This value is in TICKS: 20 ticks equal one second.
  #Advanced config only.
  TimeInTheAir: 2
  #Damage the player depending on how high they are?
  #This shops players using the Flight check to prevent fall damage.
  DamagePlayer: true
  #What command do you want to execute when someone is detected for flying?
  FlightCommand: # 
  #If TeleportDownOnly is set to false, players are dragged back to where they were before they tried to fly.
  #If TeleportDownOnly is true, players are dragged to the ground from the current location where they are flying.
  #It is recommended to enable TeleportDownOnly on Skywars servers. 
  TeleportDownOnly: false
  #Enabling DetectJesus will make the Flight check believe the ground is 2 blocks lower if a player is on water.
  #This means any player standing on top of the water for an extended period of time will be dragged into it.
  DetectJesus: true
