### ISSUE TITLE
Replay System

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#5]
This is just a suggestion

But an AntiCheat called [Cardianal AntiCheat](https://www.spigotmc.org/resources/cardinal-anticheat-community-edition-1-8-x.72084) & it has a replay system

So when someone gets banned/kicked it creates a zipped file & moves it to a folder (eg /CAC/replays) and when you run the command /cac replay it opens a GUI where you can select replays (They automatically delete after a specified amount of days to save space)

I feel like this would be a nice feature to have seeing as it's a premium plugin and CAC is free

**Comment by joehot200** [comment]
This is actually a good idea, which I could definitely look into. It may be a few months before this becomes reality, though. When it says "replay", does this mean you literally see the players performing the actions that they did when detected?

**Comment by Jakaboii** [comment]
Yes, it shows everything the player did before they got banned

The one CAC uses is a bit finicky though, so I'm not sure how much it saves before the player gets banned (So if it shows 5 minute footage before the player got banned, or 1 minute footage)

**Comment by ghost** [comment]
Added in 11.93 :P

**Comment by Jakaboii** [comment]
WOOOOO
