### ISSUE TITLE
11.82-current: AntiKnockback false positives 

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#52]
**Videos:**
- False flagging against a wall: https://youtu.be/xn4etm5pGcQ

**Other information:**
In other cases, AntiKnockback _may_ cause false positives in cases where the player is hit into a block, rather than the block being immediately behind the player.

EDIT: Supposedly resolved in 11.85, but no.
Further testing shows that it will false positive on 1.8 servers, but not on 1.16 ones.

**Comment by dodofan** [comment]
@joehot200 Updated with a similar but very bad issue.

**Comment by joehot200** [comment]
Fixed for 11.85

**Comment by dodofan** [comment]
Not fixed in 11.85. Reopening issue.

**Comment by ghost** [comment]
Fixed for 11.86.
