### ISSUE TITLE
Console errors with the latest version of Anti Aura v11.8

### ISSUE THREAD

**Issue by AngieC233** [joehot200/AntiAura#53]
Latest version of anti-aura
[00:15:27] [Server thread/INFO]: [AntiAura] Enabling AntiAura v11.8
Minecraft server version 1.15.2
This server is running Paper version git-Paper-327 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Console is spamming with these errors occasionally:
https://pastebin.com/K5R1YMtu

**Comment by ghost** [comment]
Resolved in 11.81.
