### ISSUE TITLE
11.81: NPE upon joining server

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#56]
**Pastebin:** https://pastebin.com/Gwf4GTHb

**AntiAura version:** 11.81

**Server version:** Paper version git-Paper-347 (MC: 1.15.2)

**Minecraft version:** 1.15.2 

**Detailed Description:**
It occurred as soon as I rejoined after I was kicked for hacking.

**Comment by joehot200** [comment]
I believe fixed for 11.84. Please reopen (or create a new issue) if the error occurs in future.
