### ISSUE TITLE
Clarify /aconfig option

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#58]
![image](https://user-images.githubusercontent.com/29691919/84572774-54db0580-ad6a-11ea-82dd-bf26bf218319.png)

As you can see, the instructions say to use /aconfig and not /aconfiga.

**Comment by joehot200** [comment]
Does this occur even when using /aconfiga?

**Comment by ghost** [comment]
The image shown IS aconfiga...

The basic configuration only has strictness values, as you know.

**Comment by joehot200** [comment]
Fixed for 11.85
