### ISSUE TITLE
11.72: NoFall bypass

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#6]
**Screenshot (or a video recording):** https://youtu.be/JSxsVozqeF8

**AntiAura version:** 11.72

**Server version:** CraftBukkit version git-Spigot-56f8471-3e3818b (MC: 1.14.4)

**Minecraft version:** 1.14.4

**Hacked client:** Wurst 7.1.2 

**Check(s) config (if applicable):**
Included in the video.

**Detailed description of the issue:**
Falling is sometimes not checked by NoFall. It works in other cases, but in the case shown above, it doesn't.

**Additional details:**
ViaVersion isn't present.

**Comment by dodofan** [comment]
Possible correlation with minor NoFall bypass showcased on July 5, 2020 in a Discord stream.

**Comment by joehot200** [comment]
Fixed for 11.95: NoFall was checking from the **last block the player was stood on**, meaning it was not taking the jumping into account.
