### ISSUE TITLE
11.81: Bubble columns not properly checked by Flight

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#60]
**Screenshot (or a video recording):** https://youtu.be/Y8ta-weoENQ

**AntiAura version:** 11.81 dev build (confirmed on official 11.81 jar)

**Server version:**  Paper version git-Paper-348 (MC: 1.15.2)

**Minecraft version:** 1.15.2

**Hacked client:** None

**Check(s) config (if applicable):**
Provided in the video.

**Comment by joehot200** [comment]
Fixed for 11.86
