### ISSUE TITLE
11.81: Could not pass event PlayerVelocityEvent

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#61]
**Pastebin Link:** https://pastebin.com/9cPrgcmR

**Server Version:** Paper 1.8.8

**Reproduction Notes:**
Getting hit by anything (mob, explosion), but doesn't always happen. Probably prevents Knockback check from working, I'd assume. Not really sure if this is affecting why it takes me 18 hits with a sharp 5 diamond sword to kill a skeleton, but we'll see.

**Comment by joehot200** [comment]
Fixed for 11.83
