### ISSUE TITLE
11.81: Random speed issues?

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#62]
This is sort of an informal issue, because I don't know how to describe it.

It seems that this version has some very strange issues regarding Speed (such as once you get flagged once, you just keep getting flagged), and I would like to ask others if they have been experiencing the same thing too. This might be because of the changes to Speed made in 11.81. 

**Video:** https://youtu.be/QNcEG5q9RYI (on 11.83)

**Comment by dodofan** [comment]
I do want to note that this has required me to actually disable the Speed check temporarily until I can get a working fix :(

**Comment by joehot200** [comment]
Try increasing LowerAmount (under Speed), perhaps? It's just a suggestion. Like, raise it by 3 or 4. See how it goes.

**Comment by dodofan** [comment]
IDK what you did, but in terms of Speed issues:

- My Speed, FastEat, and NoSlow are actually kicking super fast now. Before, Speed NEVER kicked, and FastEat/NoSlow took a bit.

**Comment by dodofan** [comment]
Also, nonetheless, Speed shouldn't be doing what it did in the first video I posted at all anyway, right?

**Comment by ghost** [comment]
Probably resolved by increasing LowerAmount to prevent violation stacking.

**Comment by dodofan** [comment]
Issue #133 indicates the problem may not have been resolved. Additionally, further informal reports in the Discord corroborate this issue's validity.

**Comment by joehot200** [comment]
Believe the problem is solved.

**Comment by dodofan** [comment]
Present on 11.90 (just happened to me) @joehot200
