### ISSUE TITLE
Could not pass event BlockBreakEvent and EntityDamageByEntityEven errors

### ISSUE THREAD

**Issue by AngieC233** [joehot200/AntiAura#63]
Paper version git-Paper-353 (MC: 1.15.2)
AntiAura v11.81

Console spamming with errors

https://pastebin.com/STVRhV23

**Comment by AngieC233** [comment]
Update : It seems with updated Paper version git-Paper-355 (MC: 1.15.2), it doesn't spam errors anymore for now

**Comment by joehot200** [comment]
I couldn't find a clear issue here either, so I think I'll close it. Please don't hesitate to reopen if it occurs again.
