### ISSUE TITLE
11.81: AntiAura is making hits do "less" damage?

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#64]
**Server version:** 1.8.8

Without AntiAura 11.82, it takes two hits with a Sharpness V diamond sword to kill a skeleton.

With AntiAura 11.82, it takes eighteen.

**This occurs even with all Killaura and combat related checks disabled.**

**Comment by dodofan** [comment]
If this does prove true, this issue should be assigned HIGHEST-PRIORITY (or if related to issue 61, close this one entirely). It's pretty major.

**Comment by joehot200** [comment]
Which killaura check? Try disabling one by one to see.

**Comment by ghost** [comment]
Is it related to Killaura? How can you be sure?

**Comment by joehot200** [comment]
Some killaura checks (eg headmove, reach) cancel damage. I can't be 100% sure of course.

**Comment by dodofan** [comment]
To the extent of this? 

I want to point out that with the same config on 1.15.2, hits go through normally. This _might_ be because of the different combat system, however.

**Comment by dodofan** [comment]
Well, since there's been no response, I have confirmed that after disabling all Killaura checks, this is still occurring. 

There have been some other errors not directly related to AntiAura, but I'm unsure if that is why.

**Comment by A248** [comment]
I cannot reproduce this issue on a Paper 1.8.8 (4c7641d) test server with only AntiAura and ProtocolLib.

**Comment by joehot200** [comment]
Huh....

Thanks @dodofan and @A248. I will put this at high priority and test it on 1.8 when I can.

**Comment by ghost** [comment]
So interestingly enough, after I reset my configurations this no longer happened. It might have been an issue with Violations again?

**Comment by A248** [comment]
I should note, I was using 11.82 to test.

**Comment by joehot200** [comment]
Cannot reproduce
