### ISSUE TITLE
11.82: Could not pass BlockBreakEvent

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#65]
**Pastebin Link:** https://pastebin.com/9LJ5ff7Q
Second Pastebin Link on completely fresh config/aconfig files with modified commands for Violations: https://pastebin.com/yYdPm4gT 

**Server Version:** Paper 1.8.8

**Reproduction Notes:**
Using a nuker hack in creative which triggers a flurry of FastBreak flags causes this to happen. This probably isn't the only time it will happen though, and it should still be fixed.
*This seems to be different from #63.*

**Comment by joehot200** [comment]
Please could you duplicate this with a default configuration. Sorry if it's a bother, the error is useful but I can't quite seem to pin down which config option it would be. Maybe something in FastBreak?

**Comment by dodofan** [comment]
I have updated a second pastebin link with it happening @joehot200, take a look and see if it is different
