### ISSUE TITLE
Swimming triggers Flight checks

### ISSUE THREAD

**Issue by AngieC233** [joehot200/AntiAura#67]
Anti Aura  version 11.82
Paper version git-Paper-370 (MC: 1.15.2)

Swimming triggers flight checks

https://pastebin.com/v2MK7Yaq

**Comment by joehot200** [comment]
Do you know where the player was swimming? Was it just ordinary water / sea, or was it some sort of man-made waterway? A screenshot would be helpful if it's anything specific.

Currently couldn't duplicate when swimming normally but I'll revisit this at some point for more testing.

**Comment by joehot200** [comment]
Fixed in 11.8301
