### ISSUE TITLE
11.82: Jumping up on edge of fence flags Flight

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#69]
**Screenshot (or a video recording):** https://youtu.be/kPk2nO5remQ

**AntiAura version:** 11.82

**Server version:** Paper version git-Paper-370 (MC: 1.15.2)

**Minecraft version:** 1.15.2 

**Check(s) config (if applicable):**
Provided in the video.

**Detailed description of the issue:**
Steps to reproduce:
1) Sneak and go to the edge of a fence over an air block.
2) Jump up and down and you should be flagged very soon.

**Additional details:**
Sometimes flags Spider and Jump too (but with stone bricks) 
Issue might be related to the blocks not being checked properly at all?

**Comment by joehot200** [comment]
Note to self: Occurs only if StrictMode is enabled (it is disabled by default).

**Comment by dodofan** [comment]
Confirmed on 11.84 with connected stone brick walls.

**Comment by ghost** [comment]
Claimed to have been fixed in 11.87.
