### ISSUE TITLE
11.82: Could not pass BlockBreakEvent/EntityDamageByEntityEvent (caused by something related to mcMMO)

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#70]
**Pastebin:** https://pastebin.com/UhS4dmjR** 

**Version:** 1.8.8 Paper

**Additional details:**
nossr50 is a mcMMO dev, so I assume this is somewhat related to it.
Seems different from #63 and #65 too.

**Comment by joehot200** [comment]
Do you have McMMO installed? If so, which version & from where? If you could send me the jar that'd be helpful too.

**Comment by ghost** [comment]
Yes. It's the classic version and the latest build for 1.8. I think they have a Jenkins for it?

**Comment by joehot200** [comment]
Could I have the link?

**Comment by dodofan** [comment]
I can't find the link, sorry. Have you tried searching yourself? I have the actual plugin purchased on Spigot, but I'm not sure if I should be sharing that if there really isn't a Jenkins.
