### ISSUE TITLE
11.82: Jesus needs improving

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#71]
**Video:** https://youtu.be/DrwzEKEtDNs

**Version:** 1.8.8 Paper

**Client:** LiquidBounce (the user in the video)

**Additional details:**
Went from default settings to strict settings, and it still bypassed, so...
**EDIT:** I actually forgot to use advanced config, so all the values you see here are useless. However, this still shouldn't work at all.

I'm honestly thinking that maybe the Flight check needs a recode?

**Comment by joehot200** [comment]
Looks like a Jesus bypass rather than Flight. I know that the Flight check is intended to block Jesus too, however I have renamed the bug to make it more evident what the issue is.

**Comment by ghost** [comment]
It happened over land too I think @joehot200 i will try and get a video

**Comment by joehot200** [comment]
Flight jesus blockage has been improved as of 11.8301. Please open a new ticket if Flight is being too slow. Cheers.
