### ISSUE TITLE
[BYPASS] AutoBow & BowAimbot

### ISSUE THREAD

**Issue by Jakaboii** [joehot200/AntiAura#73]
## Troubleshooting Information

**AntiAura version:** 11.83

**Server version:** Paper 1.8.8

**Client version:** 1.8.9

## Proof & Config

**Screenshot (or a video recording):** https://www.youtube.com/watch?v=gcPIgK2u3Wo

**Check(s) config (if applicable):** https://hatebin.com/lrilnhpdyw

## Issue Information

**Detailed description of the issue:** Using NoSlowDown, I can still run at normal speed while using a bow (Also with BowAimbot on)

**Steps to reproduce:** Use probably any hacked client, I've only tested it on 1, turn on NoSlowDown & BowAimbot then run while aiming

**Additional Information:** It doesn't work when sprinting and jumping, but does work when normal sprinting & just normal jumping

**Comment by joehot200** [comment]
Fixed for 11.84
