### ISSUE TITLE
11.84: Jumping on iron bars flags NoFall

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#80]
**Media:** 
Video: https://youtu.be/FO5nEgMtp9w
NoFall type: https://cdn.discordapp.com/attachments/722118765814349834/731728450624290877/unknown.png

**AntiAura version:** 11.84 (silent 1)

**MC version:** Paper version git-Paper-372 (MC: 1.15.2)

**Additional details:**
Doesn't seem to work on stuff like fences/stone bricks.

EDIT (7/27): The issue is probably related to #33, which apparently didn't get fixed :(

**Comment by dodofan** [comment]
Unmilestoning for now.

**Comment by joehot200** [comment]
Cant duplicate on 11.93-1.
