### ISSUE TITLE
11.84: Sprinting into cobweb flags Speed 

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#81]
**Media:** https://youtu.be/t_HpTDUAwGE

**AntiAura version:** 11.84

**MC version:** Paper version git-Paper-372 (MC: 1.15.2)

**Additional details:**
(SEPARATE ISSUE BUT RELATED TO COBWEBS) Standing in a cobweb while falling might flag Flight sometimes.

**Comment by joehot200** [comment]
Fixed for 11.87
