### ISSUE TITLE
11.84: Ice boating will flag Speed when used over time

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#82]
**Media:**
https://youtu.be/pSYahqkap8Y

**AntiAura version:** 11.84

**MC version:** Paper version git-Paper-372 (MC: 1.15.2)

**Additional details:**
Config is in the video.

**Comment by dodofan** [comment]
Unmilestoning for now.

**Comment by joehot200** [comment]
Pretty sure we fixed this as we tested it on endcraft.net not long ago, so closing
