### ISSUE TITLE
11.84: Swimming through water with head poking flags Flight

### ISSUE THREAD

**Issue by ghost** [joehot200/AntiAura#83]
**Media:** https://youtu.be/nHHBQpOSNPE

**AntiAura version:** 11.84

**Server version:** Paper version git-Paper-372 (MC: 1.15.2)

**Comment by joehot200** [comment]
Fixed for 11.86

**Comment by dodofan** [comment]
Reintroduced in 11.86-4.

**Comment by joehot200** [comment]
This was fixed / Can't dupe in 11.93-1
