### ISSUE TITLE
Expand UnlikelyInteract to block unlikely placements

### ISSUE THREAD

**Issue by joehot200** [joehot200/AntiAura#85]
As of 11.85, UnlikelyInteract only blocks impossible inventory opening attempts.

In future, it should also block other impossible acts - such as placing blocks on a face that cannot be seen - as well as unlikely acts - such as accurately scaffolding with fast head movement going on.

**Comment by dodofan** [comment]
My simple idea of something like this has come true :)

**Comment by joehot200** [comment]
Did the cannot be seen bit a while ago, but I'll have to look at "unlikely" acts later.
