### ISSUE TITLE
Geyser Bedrock Floodgate Support

### ISSUE THREAD

**Issue by myavuzokumus** [joehot200/AntiAura#90]
https://github.com/GeyserMC/Geyser
https://github.com/GeyserMC/Floodgate

Geyser protocol for bedrock to java version server. And players can join on bedrock version to java edition. But some cheat checkers false positive for bedrock players. Can you add check for this?
Floodgate can put prefix front of player name. And if you add this settings to config, we can bypassed bedrock players.
Example

Bedrock-Prefix: '.'

If player name have front of ".", antiaura will be bypassed this player.

**Comment by joehot200** [comment]
@OverBrave I could definitely do this.

It may also be possible for me to modify AntiAura's checks to work differently with bedrock players. How different are actions from bedrock players compared to java players?

**Comment by myavuzokumus** [comment]
Hmm, i don't know but some of actions are absolutely different.

**Comment by joehot200** [comment]
Moved to high priority, as should not be difficult to implement.

Added Bedrock Compatibility as a mid-priority feature request: https://github.com/joehot200/AntiAura/issues/91

**Comment by joehot200** [comment]
DONE.
