### ISSUE TITLE
Bedrock Client (using Geyser) compatibility

### ISSUE THREAD

**Issue by joehot200** [joehot200/AntiAura#91]
Using Geyser, Bedrock clients can join Java Edition servers.

With Floodgate, bedrock players can have a name prefix. Therefore:

**Modify behaviours for players with a name prefix to make AntiAura compatible with the bedrock edition.**

(note: cannot guarantee that it will be possible)

According to CamperJones: 

> @joehot200 Actualy the prefix can be disable from the GeyserProxy, in my case I dont use. Can you do a permission node to not detecting cheats ? In my server I put a tag [Bedrock] to the players.
the UUID of the Geyser/floodgate is totally different, even if the player join with the same "nickname".
Java UUID: 49d245a8-35eb-3b13-965a-8cfc03f85189
flodgate geyser UUID: 00000000-0000-0000-0009-01fe7478e830
if it helps in something

**Comment by Tim203** [comment]
Please note that linked-accounts are also a thing, so I would recommend using the Floodgate Api. If you haven't joined our discord yet, I would recommend joining. Floodgate is undergoing a rewrite right now, so the Api will change.

**Comment by joehot200** [comment]
@Tim203 Thanks for the info, that's useful - I don't know too much about Floodgate yet. When I get around do implementing Floodgate support I'll definitely join Discord and all that good stuff.

**Comment by joehot200** [comment]
@Tim203 Could I have your Discord link? The link on your website (http://discord.geysermc.org/) doesn't function for me - it leads me to an empty channel and doesn't join a server. Thanks!

**Comment by Tim203** [comment]
This is the invite you get when you type discord.geysermc.org: https://discord.com/invite/7ZDSKa5 and if that one doesn't work then I made this one: https://discord.gg/sxApnD (that link will expire in one day)

**Comment by joehot200** [comment]
DONE.

(Thanks @Tim203 )
